version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/src/deploy
    overwrite: true
permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user  
    
hooks:
  AfterInstall:
    - location: scripts/stop
      timeout: 60
  ApplicationStart:
    - location: scripts/start
      timeout: 60
